### ISSUE TITLE
Ctrl+Click on terms with the same name across different files no longer works

### ISSUE THREAD

**Issue by chandradeepdey** [FStarLang/fstar-vscode-assistant#35]
`A.fst`
```fst
module A

let x = string
```

`B.fst`
```fst
module B

open A

let x = x
```

Ctrl+Clicking on the RHS x used to bring up the line in A.fst before. In 0.7.0 it just shifts the cursor to the LHS x.

**Comment by gebner** [comment]
Thanks for catching that one!  It should be fixed by e0357e56747285c1cdf2bb73eb948a93cf861861.  The fix is included in the latest 0.7.2 release and should be coming to your vscode any moment!

**Comment by chandradeepdey** [comment]
Thank you!
