### ISSUE TITLE
Extension does not do anything besides syntax highlighting and detection of the language

### ISSUE THREAD

**Issue by tranquillity-codes** [FStarLang/fstar-vscode-assistant#39]
No error is reported, just, no autocomplete or anything becomes available. Both `fstar.exe` and `z3` are on path, and
```
$ fstar.exe --ide hello.fst
{"kind":"protocol-info","version":2,"features":["autocomplete","autocomplete/context","compute","compute/reify","compute/pure-subterms","describe-protocol","describe-repl","exit","lookup","lookup/context","lookup/documentation","lookup/definition","peek","pop","push","search","segment","vfs-add","tactic-ranges","interrupt","progress"]}
```
How does one set up the extension to function?

**Comment by nikswamy** [comment]
Can you enable the debugging option in the extension and paste the contents of Output from F* VSCode Assistant.

<img width="1566" alt="image" src="https://github.com/FStarLang/fstar-vscode-assistant/assets/6163359/a62dd2b9-18cb-4241-ba3d-214485b5420d">

I'm including an image to show where you can find it. But, pasting what you see in plain text would be nice

**Comment by tranquillity-codes** [comment]
Seems like I get
```
fstar.exe does not support full-buffer queries.
fstar.exe does not support full-buffer queries.
```
And that's it. I am on
```
$ fstar.exe --version
F* 2023.02.01~dev
platform=Linux_x86_64
compiler=OCaml 4.14.1
date=unset 
commit=v2023.02.01
```
nixpkgs seems to have gotten an update, and after updating, the extension seems to function correctly! 

I had no idea there was a debug console in vs code (still new to vs code), thanks! Closing!
