### ISSUE TITLE
Formatting deletes comments

### ISSUE THREAD

**Issue by Johanmyst** [FStarLang/fstar-vscode-assistant#4]
Hi!

Really nice to see a plugin like this again and in general it works reasonably well. However, when saving & using formatting, all comments get deleted.

**Comment by nikswamy** [comment]
Thanks for trying it out and reporting this issue!

I can repro the behavior of losing comments when using the format selection or format document features. Will work on a fix.

But, can you say more about losing comments on saving? That's a surprise.

**Comment by Johanmyst** [comment]
Hi Nik,

No worries!

> But, can you say more about losing comments on saving? That's a surprise.

Sorry, I should've mentioned this is because I use format-on-save in VSCode to automatically apply the formatter when saving. I should've said "comments lost on formatting" rather than "on saving".

Kindly,

**Comment by nikswamy** [comment]
Fixed in https://github.com/FStarLang/FStar/commit/286f9cb411e19e00b85f1302fb584126b81a657e
