### ISSUE TITLE
Highlight potentially dangerous keywords like admit and assume

### ISSUE THREAD

**Issue by klinvill** [FStarLang/fstar-vscode-assistant#48]
`admit` and `assume` are very helpful when working on proofs, allowing type-checking to succeed where it might not otherwise. These keywords are often left in as placeholders for future work. Unfortunately, when scanning a module it's easy to miss these keywords. It would be nice if the F* extension highlighted these keywords in some way, potentially by coloring them orange. Such a coloring should allow readers to easily notice occurrences of admit and assume they might otherwise miss if not explicitly looking for them.

A bonus use case could be issuing a warning when a function is encoded as admit (warned about in https://github.com/FStarLang/FStar/wiki/Sliding-admit-verification-style), although I'd imagine such a warning should probably be handled in F*'s implementation rather than in the VSCode extension.

**Comment by klinvill** [comment]
Thanks @gebner! I'm seeing `admit` highlighted in red (which is great), but it looks like `assume` is highlighted the same as `assert` for me (in purple). Maybe this is because `assume` is also listed as a keyword, I think here: https://github.com/FStarLang/fstar-vscode-assistant/blob/087a34156e2e558b52e3ff5d6ff0fff838f0f066/syntaxes/fstar.tmLanguage.json#L13

Here's what it looks like for me using extension 0.15.0:
![image](https://github.com/user-attachments/assets/c44d1de1-acea-4df8-8e47-868ca4537a65)

**Comment by gebner** [comment]
Oh, thank you for testing the change! ❤️  I totally missed that.
