### ISSUE TITLE
fstar.exe does not support full-buffer queries

### ISSUE THREAD

**Issue by chandradeepdey** [FStarLang/fstar-vscode-assistant#6]
I'm getting the following -
```
$ fstar.exe --ide A.fst
{"kind":"protocol-info","version":2,"features":["autocomplete","autocomplete/context","compute","compute/reify","compute/pure-subterms","describe-protocol","describe-repl","exit","lookup","lookup/context","lookup/documentation","lookup/definition","peek","pop","push","search","segment","vfs-add","tactic-ranges","interrupt","progress"]}
```

Is there a particular branch or flag that enables `full-buffer` and the rest? I installed with the opam dev-repo method.
```
$ fstar.exe --version
F* 2023.03.22~dev
platform=Linux_x86_64
compiler=OCaml 4.13.1
date=2023-03-29 13:43:00 -0300
commit=3cb6386009297ebc0f3a287cff62082320b765b4
```

**Comment by nikswamy** [comment]
Thank you for trying it... but this is really on the bleeding edge. You need to build this F* PR from sources in order to use this extension. https://github.com/FStarLang/FStar/pull/2853

**Comment by nikswamy** [comment]
We expect to do a binary release with support for fstar-vscode-assistant in the next week or so

**Comment by nikswamy** [comment]
This is in F* master now and you can install a full-buffer-capable fstar.exe using the dev-repo method you mentioned.
A new binary release will come out soon.

**Comment by chandradeepdey** [comment]
Thank you!
